### ISSUE TITLE
Comprobación con compañero

### ISSUE THREAD

**Issue by momah** [alu4543/tareas-iniciales-alu4543#2]
Creando un issue para la comprobación de codigo con compañero AdCalzadilla

**Comment by alu4543** [comment]
Creando un issue para la comprobación de codigo con compañero AdCalzadilla

**Comment by AdCalzadilla** [comment]
Enlace donde se puede probar el código html. [Aquí](http://jseditor.proyectosbds.com/welcome/130/edit)

**Comment by momah** [comment]
He consultado el enlace,
Gracias
issue has been resolved and closed.
